=== nightlabs/org.nightlabs.jfire.max/src/org/nightlabs/jfire/jbpm/extensionI18n/processdefinition-extension_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:jfire.org:processdefinition-extension_1_0"
	elementFormDefault="qualified">
	

	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			this is a schema to define the process definition extension file used to
			extend the process definition JBPM file.
		</xsd:documentation>
	</xsd:annotation>

	<xsd:element name="description">
		<xsd:complexType>
			<xsd:attribute name="language" type="xsd:string" use="required">
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="icon">
		<xsd:complexType>
			<xsd:attribute name="file" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="name">
		<xsd:complexType>
			<xsd:attribute name="language" type="xsd:string" use="required">
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="transition">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			the UserExecutube Attribute define if the Transition node is executable
			The default value of 'userExecutable' should be true if not defined.
		</xsd:documentation>
	</xsd:annotation>
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="description" />
				<xsd:element ref="name" />
				<xsd:element ref="icon" maxOccurs="1"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string" use="required" />			
			<xsd:attribute name="userExecutable" type="xsd:boolean" use="optional" />
		</xsd:complexType>
	</xsd:element>

	
	<xsd:element name="node">
	<xsd:annotation>
	<xsd:documentation xml:lang="en">
	 Each node contains a I18I name, I18I Description, and a graphical icon.
	
	 If a state definition is marked as publicState, it will be exposed to other organisations
	 by storing it in both the OfferLocal and the Offer instance. If it is not public,
	 it is only stored in the OfferLocal, it s true, if it shall be registered in the non-local instance and therefore published to business partners.
	 The default value of 'publicState' should be false if not defined.
	</xsd:documentation>
	</xsd:annotation>
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="description" />
				<xsd:element ref="name" />
				<xsd:element ref="icon" maxOccurs="1"/>
				<xsd:element ref="transition" />
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="publicState" type="xsd:boolean" use="optional" />
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="start-state">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="description" />
				<xsd:element ref="name" />
				<xsd:element ref="icon" maxOccurs="1"/>
				<xsd:element ref="transition" />
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="publicState" type="xsd:boolean" use="optional" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="state">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="description" />
				<xsd:element ref="name" />
				<xsd:element ref="transition" />
				<xsd:element ref="icon" maxOccurs="1"/>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="publicState" type="xsd:boolean" use="optional" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="end-state">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="description" />
				<xsd:element ref="name" />
				<xsd:element ref="icon" maxOccurs="1"/>
			</xsd:choice>
			<xsd:attribute name="publicState" type="xsd:boolean" use="optional" />
			<xsd:attribute name="name" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="process-definition-extension">
	<xsd:annotation>
		<xsd:documentation xml:lang="en">
			the Process definition Document can contain only one start state node
		</xsd:documentation>
	</xsd:annotation>
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="node" />
				<xsd:element ref="start-state" maxOccurs="1" />
				<xsd:element ref="state" />
				<xsd:element ref="end-state" />
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>


</xsd:schema>

=== nightlabs/org.nightlabs.jfire.max/src/org/nightlabs/jfire/trade/jbpm/invoice/vendordraft/processdefinition-extension.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<process-definition-extension 
xmlns="urn:jfire.org:processdefinition-extension_1_0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="urn:jfire.org:processdefinition-extension_1_0 http://www.jfire.org/schema/processdefinition-extension_1_0.xsd"
name="dev.jfire.org:Invoice.Vendor">
	<start-state name="dev.jfire.org:created">
		<name language="de">erzeugt</name>
		<description language="de">erzeugt</description>
		<name language="en">created</name>
		<description language="en">created</description>
		<icon file="" />
		<transition name="abort">
			<name language="de">abbrechen</name>
			<description language="de">abbrechen</description>
			<name language="en">abort</name>
			<description language="en">abort</description>
			<icon file="" />
		</transition>
		<transition name="finalize">
			<name language="de">finalisieren</name>
			<description language="de">finalisieren</description>
			<name language="en">finalize</name>
			<description language="en">finalize</description>
			<icon file="" />
		</transition>
		<transition name="dev.jfire.org:bookImplicitely"
			userExecutable="false">
			<name language="de">buchen-implizit</name>
			<description language="de">buchen-implizit</description>
			<name language="en">bookImplicitely</name>
			<description language="en">bookImplicitely</description>
			<icon file="" />
		</transition>
	</start-state>
	<state name="dev.jfire.org:finalized">
		<name language="de">finalisiert</name>
		<description language="de">finalisiert</description>
		<name language="en">finalized</name>
		<description language="en">finalized</description>
		<icon file="" />
		<transition name="dev.jfire.org:book">
			<name language="de">buchen</name>
			<description language="de">buchen</description>
			<name language="en">book</name>
			<description language="en">book</description>
			<icon file="" />
		</transition>
	</state>
	<end-state name="dev.jfire.org:aborted">
		<name language="de">abgebrochen</name>
		<description language="de">abgebrochen</description>
		<name language="en">aborted</name>
		<description language="en">aborted</description>
		<icon file="" />
	</end-state>
	<state name="dev.jfire.org:doubtful">
		<name language="de">zweifelhaft</name>
		<description language="de">zweifelhaft</description>
		<name language="en">doubtful</name>
		<description language="en">doubtful</description>
		<icon file="" />
		<transition name="dev.jfire.org:pay">
			<name language="de">zahlen</name>
			<description language="de">zahlen</description>
			<name language="en">pay</name>
			<description language="en">pay</description>
			<icon file="" />
		</transition>
		<transition name="bookUnreceivable">
			<name language="de">buchen-unempfangbar</name>
			<description language="de">buchen-unempfangbar</description>
			<name language="en">bookUnreceivable</name>
			<description language="en">bookUnreceivable</description>
			<icon file="" />
		</transition>
		<transition name="trust">
			<name language="de">vertrauen</name>
			<description language="de">vertrauen</description>
			<name language="en">trust</name>
			<description language="en">trust</description>
			<icon file="" />
		</transition>
	</state>
	<end-state name="dev.jfire.org:uncollectable">
		<name language="de">nicht-beitreibbar</name>
		<description language="de">nicht-beitreibbar</description>
		<name language="en">uncollectable</name>
		<description language="en">uncollectable</description>
		<icon file="" />
	</end-state>
	<end-state name="dev.jfire.org:paid">
		<name language="de">bezahlt</name>
		<description language="de">bezahlt</description>
		<name language="en">paid</name>
		<description language="en">paid</description>
		<icon file="" />
	</end-state>
	<state name="dev.jfire.org:booked">
		<name language="de">gebucht</name>
		<description language="de">gebucht</description>
		<name language="en">booked</name>
		<description language="en">booked</description>
		<icon file="" />
		<transition name="dev.jfire.org:send">
			<name language="de">senden</name>
			<description language="de">senden</description>
			<name language="en">send</name>
			<description language="en">send</description>
			<icon file="" />
		</transition>
	</state>
	<node name="dev.jfire.org:bookedUnreceivable">
		<name language="de">gebucht-unempfangbar</name>
		<description language="de">gebucht-unempfangbar</description>
		<name language="en">bookedUnreceivable</name>
		<description language="en">bookedUnreceivable</description>
		<icon file="" />
		<transition name="endAsUncollectable">
			<name language="de">endet-als-nicht-beitreibbar</name>
			<description language="de">endet-als-nicht-beitreibbar</description>
			<name language="en">endAsUncollectable</name>
			<description language="en">endAsUncollectable</description>
			<icon file="" />
		</transition>
	</node>
	<state name="dev.jfire.org:sentReminder">
		<name language="de">Mahnung-gesendet</name>
		<description language="de">Mahnung-gesendet</description>
		<name language="en">sentReminder</name>
		<description language="en">sentReminder</description>
		<icon file="" />
		<transition name="sendPreCollectionLetter">
			<name language="de">letzte-Mahnung-senden</name>
			<description language="de">letzte-Mahnung-senden</description>
			<name language="en">sendPreCollectionLetter</name>
			<description language="en">sendPreCollectionLetter</description>
			<icon file="" />
		</transition>
		<transition name="dev.jfire.org:pay">
			<name language="de">zahlen</name>
			<description language="de">zahlen</description>
			<name language="en">pay</name>
			<description language="en">pay</description>
			<icon file="" />
		</transition>
		<transition name="doubt">
			<name language="de">anzweifeln</name>
			<description language="de">anzweifeln</description>
			<name language="en">doubt</name>
			<description language="en">doubt</description>
			<icon file="" />
		</transition>
	</state>
	<state name="dev.jfire.org:sentPreCollectionLetter">
		<name language="de">letzte-Mahnung-gesendet</name>
		<description language="de">letzte-Mahnung-gesendet</description>
		<name language="en">sentPreCollectionLetter</name>
		<description language="en">sentPreCollectionLetter</description>
		<icon file="" />
		<transition name="doubt">
			<name language="de">anzweifeln</name>
			<description language="de">anzweifeln</description>
			<name language="en">doubt</name>
			<description language="en">doubt</description>
			<icon file="" />
		</transition>
		<transition name="dev.jfire.org:pay">
			<name language="de">zahlen</name>
			<description language="de">zahlen</description>
			<name language="en">pay</name>
			<description language="en">pay</description>
			<icon file="" />
		</transition>
	</state>
	<node name="dev.jfire.org:bookedImplicitely">
		<name language="de">gebucht-implizit</name>
		<description language="de">gebucht-implizit</description>
		<name language="en">bookedImplicitely</name>
		<description language="en">bookedImplicitely</description>
		<icon file="" />
	</node>
</process-definition-extension>

=== nightlabs/org.nightlabs.jfire.max/src/org/nightlabs/jfire/trade/jbpm/invoice/customer/local/processdefinition-extension.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<<process-definition-extension 
xmlns="urn:jfire.org:processdefinition-extension_1_0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="urn:jfire.org:processdefinition-extension_1_0 http://www.jfire.org/schema/processdefinition-extension_1_0.xsd"
name="dev.jfire.org:Invoice.CustomerLocal">
	<start-state name="dev.jfire.org:created">
		<name language="de">erzeugt</name>
		<description language="de">erzeugt</description>
		<name language="en">created</name>
		<description language="en">created</description>
		<icon file="" />
		<transition name="finalize">
			<name language="de">finalisieren</name>
			<description language="de">finalisieren</description>
			<name language="en">finalize</name>
			<description language="en">finalize</description>
			<icon file="" />
		</transition>
		<transition name="abort">
			<name language="de">abbrechen</name>
			<description language="de">abbrechen</description>
			<name language="en">abort</name>
			<description language="en">abort</description>
			<icon file="" />
		</transition>
		<transition name="dev.jfire.org:bookImplicitely"
			userExecutable="false">
			<name language="de">buchen-implizit</name>
			<description language="de">buchen-implizit</description>
			<name language="en">bookImplicitely</name>
			<description language="en">bookImplicitely</description>
			<icon file="" />
		</transition>
	</start-state>
	<state name="dev.jfire.org:finalized">
		<name language="de">finalisiert</name>
		<description language="de">finalisiert</description>
		<name language="en">finalized</name>
		<description language="en">finalized</description>
		<icon file="" />
		<transition name="dev.jfire.org:book">
			<name language="de">buchen</name>
			<description language="de">buchen</description>
			<name language="en">book</name>
			<description language="en">book</description>
			<icon file="" />
		</transition>
	</state>
	<state name="dev.jfire.org:booked" publicState="true">
		<name language="de">gebucht</name>
		<description language="de">gebucht</description>
		<name language="en">booked</name>
		<description language="en">booked</description>
		<icon file="" />
		<transition name="dev.jfire.org:send">
			<name language="de">senden</name>
			<description language="de">senden</description>
			<name language="en">send</name>
			<description language="en">send</description>
			<icon file="" />
		</transition>
		<transition name="dev.jfire.org:deliver">
			<name language="de">liefern</name>
			<description language="de">liefern</description>
			<name language="en">deliver</name>
			<description language="en">deliver</description>
			<icon file="" />
		</transition>
	</state>
	<end-state name="dev.jfire.org:aborted">
		<name language="de">abgebrochen</name>
		<description language="de">abgebrochen</description>
		<name language="en">aborted</name>
		<description language="en">aborted</description>
		<icon file="" />
	</end-state>
	<end-state name="dev.jfire.org:delivered">
		<name language="de">geliefert</name>
		<description language="de">geliefert</description>
		<name language="en">delivered</name>
		<description language="en">delivered</description>
		<icon file="" />
	</end-state>
	<node name="dev.jfire.org:sent" publicState="true">
		<name language="de">gesendet</name>
		<description language="de">gesendet</description>
		<name language="en">sent</name>
		<description language="en">sent</description>
		<icon file="" />
	</node>
	<end-state name="dev.jfire.org:paid" publicState="true">
		<name language="de">bezahlt</name>
		<description language="de">bezahlt</description>
		<name language="en">paid</name>
		<description language="en">paid</description>
		<icon file="" />
	</end-state>
</process-definition-extension>
